#!/usr/bin/env bash
# Script to connect to windows rdp server and use credentials from pass
# requires rdesktop

HOSTNAME=$1
PASSPATH=""
USERNAME="Administrator"
KEYBOARDMAP="en-us"

if [[ "$#" -lt 1 ]]; then
  echo "Usage: $(basename "$0") <hostname> [USERNAME]" >&2
  exit 1
fi 

if [[ "$#" -gt 1 ]]; then
  USERNAME=$2
fi

# Split hostname on every dot
IFS='.' read -r -a TERMS <<< "$HOSTNAME"

DOMAIN="${TERMS[-2]}.${TERMS[-1]}"
PASSPATH="servers/$DOMAIN"

for i in $(echo "${!TERMS[@]}" | rev);
do 
  if [[ ${TERMS[$i]} == "${TERMS[-2]}" || ${TERMS[$i]} == "${TERMS[-1]}" || ${TERMS[$i]} == "${TERMS[0]}" ]]; then continue; fi
  PASSPATH="$PASSPATH/${TERMS[$i]}"
done

PASSPATH="$PASSPATH/$HOSTNAME/system/$USERNAME"

PASSWORD=$(pass "$PASSPATH")
if [[ $? != 0 ]]; then
  exit 1
fi
rdesktop -u "$USERNAME" -p "$PASSWORD" -k "$KEYBOARDMAP" "$HOSTNAME"
